name: Publish Docker image on every push

on:
  push:
    branches:
    - master
    - feat/indexer-and-webapp
env:
  REGISTRY_NAME: altregistry
  OTP_VERSION: '24.3.4.1'
  ELIXIR_VERSION: '1.13.4'

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.output-step.outputs.short-sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.ALTREGISTRY_USERNAME }}
          password: ${{ secrets.ALTREGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Add outputs
        run: |
          echo "::set-output name=short-sha::${{ env.SHORT_SHA }}"
        id: output-step

      - name: Build and push image with all features
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:${{ env.SHORT_SHA }}
          build-args: |
            DISABLE_INDEXER=false
            DISABLE_READ_API=false
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_EXCHANGE_RATES_PERIOD=
            API_PATH=
            NETWORK_PATH=
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=false
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            DISABLE_BRIDGE_MARKET_CAP_UPDATER=false
            CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=
            SOCKET_ROOT=
            CHAIN_ID=
            JSON_RPC=
            COIN_NAME=
            SUBNETWORK=
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push indexer only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:indexer-latest, ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:indexer-${{ env.SHORT_SHA }}
          build-args: |
            DISABLE_INDEXER=false
            DISABLE_READ_API=true
            DISABLE_WEBAPP=true
            DISABLE_WRITE_API=true
            CACHE_EXCHANGE_RATES_PERIOD=
            API_PATH=
            NETWORK_PATH=
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=false
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            DISABLE_BRIDGE_MARKET_CAP_UPDATER=false
            CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=
            SOCKET_ROOT=
            CHAIN_ID=
            JSON_RPC=
            COIN_NAME=
            SUBNETWORK=
          cache-from: type=local,src=/tmp/.buildx-cache-new
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push webapp only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:webapp-latest, ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:webapp-${{ env.SHORT_SHA }}
          build-args: |
            DISABLE_INDEXER=true
            DISABLE_READ_API=false
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_EXCHANGE_RATES_PERIOD=
            API_PATH=
            NETWORK_PATH=
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=false
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            DISABLE_BRIDGE_MARKET_CAP_UPDATER=false
            CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=
            SOCKET_ROOT=
            CHAIN_ID=
            JSON_RPC=
            COIN_NAME=
            SUBNETWORK=
          cache-from: type=local,src=/tmp/.buildx-cache-new
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
