# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches: [feat/altlayer]

env:
  REGISTRY_NAME: altregistry
  OTP_VERSION: '24.3.4.1'
  ELIXIR_VERSION: '1.13.4'

jobs:
  push_to_registry:
    name: Push Docker image to Azure Container Registry
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 4.1.5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.ALTREGISTRY_USERNAME }}
          password: ${{ secrets.ALTREGISTRY_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout
      
      - name: Build & Push Docker image
        run: docker buildx build -t ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:latest -t ${{ env.REGISTRY_NAME }}.azurecr.io/blockscout:${{ github.sha }} -f ./docker/Dockerfile --push --platform=linux/amd64 .